# Generated by Django 4.2.20 on 2026-08-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_digest_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
